### ISSUE TITLE
duplicate symbol ___cxa_throw when linking on iOS / IL2CPP / Universal

### ISSUE THREAD

**Issue by ChristianTellefsen** [bitstadium/HockeySDK-Unity-iOS#17]
When I try to build on Unity 5.2 with the latest (1.0.8) version of HockeyApp iOS, using IL2CPP and Universal target, I get the following linker error in XCode:

duplicate symbol ___cxa_throw in:
    /Users/MegaBuild/prj/trolls2/build/trolls2/Libraries/HockeyApp/HockeyAppUnityIOS/libHockeyAppUnity.a(BITCrashCXXExceptionHandler.o)
    /Users/MegaBuild/prj/trolls2/build/trolls2/Libraries/HockeyApp/HockeyAppUnityIOS/libHockeyAppUnity.a(MSAICrashCXXExceptionHandler.o)
ld: 1 duplicate symbol for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ChristianTellefsen** [comment]
It seems to me like the library might have two copies of the same symbol.

**Comment by ChristianTellefsen** [comment]
The duplicate function seems to be coming from here, maybe you're using this library in your SDK?

https://github.com/Microsoft/ApplicationInsights-OSX/blob/master/Classes/MSAICrashCXXExceptionHandler.mm

**Comment by chrwend** [comment]
Hi Christian,

thanks for the bug report. Where did you get the HockeyApp Unity SDK from? 

Just checked the tag 1.0.8, master, and develop branch, and they worked well. I assume you are on the feature branch (add-telemetry-support).

Thank you,

-Christoph

**Comment by ChristianTellefsen** [comment]
Hi Christoph,

I believe it was downloaded from here by a colleague yesterday, it should
be the zip from the master branch.

https://github.com/bitstadium/HockeySDK-Unity-iOS

If this is not the right place the fetch from, could you direct me to the
version I should be using?

Cheers,
Christian

**Comment by chrwend** [comment]
Hi Christian,

the link you provided is correct. Please doublecheck if you are already using this.

If so, feel free to provide me with a demo project.

**Comment by ChristianTellefsen** [comment]
OK, I had the PostProcess file in the project with version 1.0.7, and the
HockeyAppiOS.cs with version 1.1.0. So I'm guessing something went wrong on
our end when upgrading.

It looks like the version we had was a combined one with iOS, Android, and
Windows. I removed this version, installing a clean 1.0.8 iOS only plugin.
It linked just fine.

Cheers,
Christian.
